(() => {
  const deck = document.querySelector('#deck'); const select = document.querySelector('#slideSelect'); const note = document.querySelector('#note'); const priority = document.querySelector('#priority'); const notesEl = document.querySelector('#notes'); const key = `html-presentation-review:${location.pathname}`; const cropKey = `${key}:crops`;
  let slides = []; let images = []; let current = { index: 0, id: 'slide-01', title: 'Folie 1' }; let notes = JSON.parse(localStorage.getItem(key) || '[]'); let imageCrops = JSON.parse(localStorage.getItem(cropKey) || '{}');
  const $ = s => document.querySelector(s); const clean = s => String(s || '').replace(/[<>]/g, '');
  function save() { localStorage.setItem(key, JSON.stringify(notes)); localStorage.setItem(cropKey, JSON.stringify(imageCrops)); renderNotes(); }
  function setCurrent(slide) { current = { index: Number(slide.index || 0), id: slide.id || `slide-${Number(slide.index || 0) + 1}`, title: slide.title || `Folie ${Number(slide.index || 0) + 1}` }; $('#slideLabel').textContent = `${current.index + 1}/${slides.length || '?'} · ${current.title}`; select.value = String(current.index); }
  function fillSelect(found) { slides = found.length ? found : Array.from({ length: 30 }, (_, index) => ({ index, id: `slide-${String(index + 1).padStart(2, '0')}`, title: `Folie ${index + 1}` })); select.innerHTML = slides.map(s => `<option value="${s.index}">${s.index + 1}. ${clean(s.title)}</option>`).join(''); setCurrent(slides[0]); }
  function inspectDeck() { try { const doc = deck.contentDocument; const found = [...doc.querySelectorAll('section.slide,[data-slide]')].map((el, index) => ({ index, id: el.id || `slide-${String(index + 1).padStart(2, '0')}`, title: el.dataset.title || el.querySelector('h1,h2')?.textContent?.trim() || `Folie ${index + 1}` })); images = [...doc.querySelectorAll('img[data-image-id]')].map((el, index) => ({ id: el.dataset.imageId || `image-${index + 1}`, title: el.alt || el.dataset.imageId || `Bild ${index + 1}` })); $('#deckName').textContent = doc.title || 'Folienreview'; fillSelect(found); fillCropImages(); } catch { fillSelect([]); } }
  function renderNotes() { $('#noteCount').textContent = `${notes.length} ${notes.length === 1 ? 'Hinweis' : 'Hinweise'}`; notesEl.innerHTML = ''; if (!notes.length) { notesEl.append($('#empty').content.cloneNode(true)); return; } notes.forEach((item, index) => { const li = document.createElement('li'); li.innerHTML = `<strong>${clean(item.slideTitle)}</strong> · ${clean(item.text)}<span class="meta">${clean(item.priority)} · ${new Date(item.createdAt).toLocaleString('de-DE')}</span><button class="delete" aria-label="Hinweis löschen">×</button>`; $('.delete', li).addEventListener('click', () => { notes.splice(index, 1); save(); }); notesEl.append(li); }); }
  window.addEventListener('message', event => { if (event.source !== deck.contentWindow || event.data?.type !== 'presentation:slidechange') return; setCurrent(event.data); });
  deck.addEventListener('load', inspectDeck); select.addEventListener('change', () => { const selected = slides.find(s => s.index === Number(select.value)); if (selected) { setCurrent(selected); deck.contentWindow.postMessage({ type: 'review:goto', index: selected.index, id: selected.id }, '*'); } });
  function add() { const text = note.value.trim(); if (!text) { note.focus(); return; } notes.push({ slideIndex: current.index, slideId: current.id, slideTitle: current.title, priority: priority.value, text, createdAt: new Date().toISOString() }); note.value = ''; save(); }
  $('#saveNote').addEventListener('click', add); note.addEventListener('keydown', e => { if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') add(); });
  function cropState() { return { imageId: $('#cropImage').value, x: Number($('#cropX').value), y: Number($('#cropY').value), scale: Number($('#cropZoom').value) / 100 }; }
  function sendCrop() { const crop = cropState(); if (crop.imageId) deck.contentWindow.postMessage({ type: 'review:crop', ...crop }, '*'); }
  function fillCropImages() { const tools = $('#cropTools'); tools.hidden = !images.length; if (!images.length) return; const list = $('#cropImage'); list.innerHTML = images.map(image => `<option value="${clean(image.id)}">${clean(image.title)}</option>`).join(''); loadCrop(); }
  function loadCrop() { const saved = imageCrops[$('#cropImage').value] || { x: 50, y: 50, scale: 1 }; $('#cropX').value = saved.x; $('#cropY').value = saved.y; $('#cropZoom').value = Math.round(saved.scale * 100); sendCrop(); }
  $('#cropImage').addEventListener('change', loadCrop); ['#cropX','#cropY','#cropZoom'].forEach(id => $(id).addEventListener('input', sendCrop)); $('#saveCrop').addEventListener('click', () => { const crop = cropState(); if (!crop.imageId) return; imageCrops[crop.imageId] = crop; save(); $('#slideLabel').textContent = 'Bildausschnitt gespeichert.'; }); $('#resetCrop').addEventListener('click', () => { const id = $('#cropImage').value; delete imageCrops[id]; loadCrop(); save(); });
  function payload() { return { schemaVersion: 2, generatedAt: new Date().toISOString(), reviewTarget: location.href, instructions: 'Setze nur die unten genannten Hinweise und Bildausschnitte um. Lass alle nicht genannten Folien, IDs, Medien und Interaktionen unverändert. Bilddateien niemals strecken oder überschreiben: nur object-fit:cover und die angegebenen CSS-Crop-Werte verwenden. Prüfe danach Offline-Funktion, Druckansicht, Tastatursteuerung und den Review-Event.', changes: notes, imageCrops: Object.values(imageCrops) }; }
  async function copyPrompt() { const p = payload(); const text = `Überarbeite die portable HTML-Präsentation gezielt nach diesem Review-JSON.\n\n${JSON.stringify(p, null, 2)}\n\nErstelle/aktualisiere außerdem CHANGELOG.md mit den umgesetzten Punkten. Keine globale Neugestaltung und keine externen Abhängigkeiten.`; try { await navigator.clipboard.writeText(text); $('#slideLabel').textContent = 'Revisionsprompt kopiert.'; } catch { download('review-prompt.txt', text, 'text/plain'); } }
  function download(name, content, type = 'application/json') { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([content], { type })); a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); }
  $('#copyPrompt').addEventListener('click', copyPrompt); $('#downloadJson').addEventListener('click', () => download('review-export.json', JSON.stringify(payload(), null, 2))); $('#printDeck').addEventListener('click', () => { deck.contentWindow.focus(); deck.contentWindow.print(); }); $('#clearNotes').addEventListener('click', () => { if (confirm('Alle lokalen Review-Hinweise löschen?')) { notes = []; save(); } });
  const themeKey = 'html-presentation-review-theme'; const setThemeLabel = () => { const value = document.documentElement.dataset.theme || 'system'; $('#themeToggle').textContent = value === 'dark' ? '◑ Dunkel' : value === 'light' ? '◒ Hell' : '◐ System'; }; const savedTheme = localStorage.getItem(themeKey); if (savedTheme) document.documentElement.dataset.theme = savedTheme; setThemeLabel(); $('#themeToggle').addEventListener('click', () => { const currentTheme = document.documentElement.dataset.theme || 'system'; const nextTheme = currentTheme === 'system' ? 'dark' : currentTheme === 'dark' ? 'light' : 'system'; if (nextTheme === 'system') { delete document.documentElement.dataset.theme; localStorage.removeItem(themeKey); } else { document.documentElement.dataset.theme = nextTheme; localStorage.setItem(themeKey, nextTheme); } setThemeLabel(); });
  fillSelect([]); renderNotes();
})();
